// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoetryManager.Web.Data;

#nullable disable

namespace PoetryManager.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510150235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PoetryManager.Web.Models.Poem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dynasty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Poems");
                });

            modelBuilder.Entity("PoetryManager.Web.Models.PoemTag", b =>
                {
                    b.Property<int>("PoemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PoemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PoemTags");
                });

            modelBuilder.Entity("PoetryManager.Web.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PoetryManager.Web.Models.PoemTag", b =>
                {
                    b.HasOne("PoetryManager.Web.Models.Poem", "Poem")
                        .WithMany("PoemTags")
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoetryManager.Web.Models.Tag", "Tag")
                        .WithMany("PoemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PoetryManager.Web.Models.Poem", b =>
                {
                    b.Navigation("PoemTags");
                });

            modelBuilder.Entity("PoetryManager.Web.Models.Tag", b =>
                {
                    b.Navigation("PoemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
